#!/system/bin/sh
    case $1 in
        ro )
			mount -o remount,ro /dev/stl6 /system;;			
        rw )
			mount -o remount,rw /dev/stl6 /system;;
        * )
            echo "Usage: $0 ro|rw";;
    esac
